# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '5b182916-1be7-4567-8108-964d86aad2f8'

  # Web app name
  webAppName: 'angular-16-client-dev'

  # Environment name
  environmentName: 'angular-16-client-dev'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
  buildConfiguration: "production"

steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
        npm run build-prod
      displayName: 'Install npm packages'

    - task: CopyFiles@2
      inputs:
        contents: 'dist/**/*'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy files to artifact staging directory'

    - task: PublishBuildArtifacts@1
      inputs:
           pathToPublish: '$(Build.ArtifactStagingDirectory)'
           artifactName: 'drop'
      displayName: 'Publish build artifacts'